# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Departamento.create(nombre: 'Amazonas')
Departamento.create(nombre: 'Ancash')
Departamento.create(nombre: 'Apurimac')
Departamento.create(nombre: 'Arequipa')
Departamento.create(nombre: 'Ayacucho')
Departamento.create(nombre: 'Cajamarca')
Departamento.create(nombre: 'Cuzco')
Departamento.create(nombre: 'Huancavelica')
Departamento.create(nombre: 'Huanuco')
Departamento.create(nombre: 'Ica')
Departamento.create(nombre: 'Junin')
Departamento.create(nombre: 'La Libertad')
Departamento.create(nombre: 'Lambayeque')
Departamento.create(nombre: 'Lima')
Departamento.create(nombre: 'Loreto')
Departamento.create(nombre: 'Madre de Dios')
Departamento.create(nombre: 'Moquegua')
Departamento.create(nombre: 'Pasco')
Departamento.create(nombre: 'Piura')
Departamento.create(nombre: 'Puno')
Departamento.create(nombre: 'San Martin')
Departamento.create(nombre: 'Tacna')
Departamento.create(nombre: 'Tumbes')
Departamento.create(nombre: 'Ucayali')
NumeroGuia.create(numero: '000001')
NumeroFactura.create(numero: '000001')
#Unit.create(nombre: 'Kilogramo', und: 'Kg')
#Measure.create(nombre: 'Sacos', und: 'sacos')
#Credito.create(nombre: 'Credito a 15 dias')
#Moneda.create(nombre: 'Nuevos Soles', simbolo: 'S/.')
#Moneda.create(nombre: 'Dolares', simbolo: '$')
